
nama = input("MASUKAN NAMA:")
umur = input("MASUKAN UMUR:")
email = input("MASUKAN EMAIL:")
asal = input("MASUKAN ASAL:")
print("----Data Kamu----")
print(f"Nama: {nama}")
print(f"Umur: {umur}")
print(f"Email: {email}")
print(f"Asal: {asal}")
